/**
 * Builds a tiny, genuinely valid one-page PDF so the demo has real bytes to
 * store, preview and download — a fake blob would break the viewer, and
 * shipping sample PDFs as assets would bloat the bundle for everyone.
 */
export function createSamplePdf(title: string, subtitle: string): Blob {
  const escape = (text: string) => text.replace(/([()\\])/g, "\\$1").slice(0, 80);

  const content = `BT /F1 22 Tf 62 720 Td (${escape(title)}) Tj ET
BT /F1 11 Tf 62 694 Td (${escape(subtitle)}) Tj ET
BT /F1 9 Tf 62 668 Td (Sample document generated by the Vault demo dataset.) Tj ET
0.6 0.6 0.72 RG 1 w 62 656 m 534 656 l S`;

  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];
  objects.forEach((body, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${body}\nendobj\n`;
  });

  const xrefStart = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets) {
    pdf += `${offset.toString().padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;

  return new Blob([pdf], { type: "application/pdf" });
}
